const CartActionTypes = {
    BUKA_TUTUP_CART: 'BUKA_TUTUP_CART',
    TAMBAH_BARANG: 'TAMBAH_BARANG',
    KURANGI_SINGKIRKAN_BARANG: 'KURANGI_SINGKIRKAN_BARANG',
    HAPUS_BARANG: 'HAPUS_BARANG'
};

export default CartActionTypes;